.PHONY: submit

submit:
	turnin --submit ans peer_eval minhpham_easchner_fs.txt
	turnin --submit ans peer_eval minhpham_minhpham_all.txt

list:
	turnin --list ans peer_eval

verify:
	turnin --verify ans peer_eval